# Generated by Django 4.2.26 on 2025-11-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_with_pi', '0002_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureresult',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='data_with_pi.plant'),
        ),
        migrations.AddIndex(
            model_name='captureresult',
            index=models.Index(fields=['-created_at'], name='data_with_p_created_f9dfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='captureresult',
            index=models.Index(fields=['plant'], name='data_with_p_plant_i_e1c2b6_idx'),
        ),
    ]
