# Generated by Django 4.2.26 on 2025-11-05 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_with_pi', '0003_captureresult_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='captureresult',
            index=models.Index(fields=['user'], name='data_with_p_user_id_f1457c_idx'),
        ),
    ]
