# Generated by Django 4.2.26 on 2025-11-06 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_with_pi', '0004_captureresult_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureresult',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='captures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='captureresult',
            name='source',
            field=models.CharField(choices=[('pi', 'Pi Capture'), ('upload', 'User Upload')], default='pi', max_length=16),
        ),
        migrations.AlterField(
            model_name='captureresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to=settings.AUTH_USER_MODEL),
        ),
    ]
