# Generated by Django 5.2.7 on 2025-11-21 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_with_pi', '0006_plant_additional_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Bỏ qua RemoveField operations vì các field này không tồn tại trong database
        # Chỉ tạo model UserCameraPreset mới
        migrations.CreateModel(
            name='UserCameraPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('settings', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['user'], name='data_with_p_user_id_9cec27_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
