# Generated by Django 5.2.7 on 2025-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_with_pi', '0007_remove_plant_common_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='english_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
