# Generated by Django 4.2.26 on 2025-11-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_with_pi', '0010_add_missing_plant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên công thức')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('recipe_type', models.CharField(choices=[('tea', 'Trà/Nước sắc'), ('juice', 'Nước ép'), ('paste', 'Cao/Thuốc đắp'), ('powder', 'Bột'), ('oil', 'Tinh dầu'), ('tincture', 'Cồn thuốc'), ('syrup', 'Siro'), ('other', 'Khác')], default='tea', max_length=20, verbose_name='Loại công thức')),
                ('treats', models.TextField(blank=True, default='', help_text='Các bệnh hoặc triệu chứng mà công thức này có thể điều trị', verbose_name='Bệnh/Triệu chứng điều trị')),
                ('benefits', models.TextField(blank=True, default='', help_text='Các lợi ích sức khỏe của công thức', verbose_name='Công dụng')),
                ('main_ingredient', models.TextField(help_text='Phần của cây sử dụng và số lượng (VD: 20-30g lá tươi hoặc 10g lá khô)', verbose_name='Nguyên liệu chính')),
                ('additional_ingredients', models.TextField(blank=True, default='', help_text='Các nguyên liệu khác cần thiết (nếu có)', verbose_name='Nguyên liệu phụ')),
                ('preparation_steps', models.TextField(help_text='Các bước chế biến chi tiết', verbose_name='Cách chế biến')),
                ('preparation_time', models.IntegerField(blank=True, help_text='Tổng thời gian cần để hoàn thành công thức', null=True, verbose_name='Thời gian chế biến (phút)')),
                ('difficulty', models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='easy', max_length=10, verbose_name='Độ khó')),
                ('usage_method', models.CharField(choices=[('oral', 'Uống'), ('topical', 'Bôi ngoài da'), ('inhale', 'Hít/Ngửi'), ('compress', 'Chườm'), ('gargle', 'Súc miệng'), ('bath', 'Ngâm tắm')], max_length=20, verbose_name='Cách dùng')),
                ('dosage', models.TextField(help_text='Liều lượng và tần suất sử dụng (VD: Uống 2-3 lần/ngày, mỗi lần 100ml)', verbose_name='Liều lượng')),
                ('duration', models.CharField(blank=True, default='', help_text='Thời gian nên sử dụng (VD: 7-10 ngày)', max_length=255, verbose_name='Thời gian điều trị')),
                ('storage', models.TextField(blank=True, default='', help_text='Cách bảo quản và thời hạn sử dụng', verbose_name='Bảo quản')),
                ('warnings', models.TextField(blank=True, default='', help_text='Các cảnh báo về tác dụng phụ, chống chỉ định, tương tác thuốc', verbose_name='Cảnh báo/Lưu ý')),
                ('contraindications', models.TextField(blank=True, default='', help_text='Những đối tượng không nên sử dụng (VD: Phụ nữ mang thai, trẻ em...)', verbose_name='Chống chỉ định')),
                ('notes', models.TextField(blank=True, default='', help_text='Các thông tin bổ sung, mẹo hay lưu ý khác', verbose_name='Ghi chú thêm')),
                ('source', models.CharField(blank=True, default='', help_text='Nguồn tham khảo của công thức (sách, bài báo, dân gian...)', max_length=255, verbose_name='Nguồn')),
                ('is_verified', models.BooleanField(default=False, help_text='Công thức đã được chuyên gia xác thực', verbose_name='Đã xác thực')),
                ('popularity', models.IntegerField(default=0, help_text='Số lượt xem hoặc sử dụng', verbose_name='Độ phổ biến')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='data_with_pi.plant', verbose_name='Cây thuốc')),
            ],
            options={
                'verbose_name': 'Công thức thuốc',
                'verbose_name_plural': 'Công thức thuốc',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plant', '-created_at'], name='data_with_p_plant_i_9efaae_idx'), models.Index(fields=['recipe_type'], name='data_with_p_recipe__f9f6e3_idx'), models.Index(fields=['-popularity'], name='data_with_p_popular_5135d0_idx')],
            },
        ),
    ]
