# Generated by Django 4.2.26 on 2025-11-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_with_pi', '0012_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Ảnh minh họa chính cho công thức', null=True, upload_to='recipes/', verbose_name='Ảnh đại diện'),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/gallery/', verbose_name='Ảnh')),
                ('caption', models.CharField(blank=True, default='', help_text='Mô tả ngắn về ảnh', max_length=255, verbose_name='Chú thích')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data_with_pi.recipe', verbose_name='Công thức')),
            ],
            options={
                'verbose_name': 'Ảnh công thức',
                'verbose_name_plural': 'Ảnh công thức',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['recipe', 'order'], name='recipe_image_idx')],
            },
        ),
    ]
